### ISSUE TITLE
Next test kicked off synchronously when plan completes?

### ISSUE THREAD

**Issue by myndzi** [tapjs/tapjs#184] opened 2015-11-05 16:22 UTC
I just updated tap and my tests started failing. I was running tests against some Reflux stores like so:

```
var count = 0;
var unlisten = Store.listen(() => {
    switch (count++) {
        case 0:
            // assertions for first trigger
        break;

        case 1:
            // assertions for next trigger, etc.
            unlisten();
        break;

        default:
            t.fail('Too many triggers');
        break;
    }
});
```

My tests started breaking, though, because apparently the last assertion before `unlisten()` triggered the next tests to start running, and since they caused the same store to emit data, the listen handler from the previous test was triggered, causing an error.

This seems to have been a recent change? I'd like to request it be changed back so that synchronous cleanup, which falls naturally at the end of the assertion code, can be executed before the next test in the set is run...

**Comment by isaacs** [comment] 2015-11-05 22:05
Can you provide a simpler use case that used to work and no longer does?  Or a way to reproduce this somehow?  I don't know what Store.listen is.

**Comment by isaacs** [comment] 2015-12-31 00:16
Closing, since I don't have a repro case.  Happy to reopen if anyone can isolate the incorrect behavior.

**Closed as completed by isaacs** 2015-12-31 00:16 UTC
