### ISSUE TITLE
Coverage not working?

### ISSUE THREAD

**Issue by djMax** [tapjs/tapjs#545] opened 2019-04-26 22:24 UTC
I've upgraded to v13 today, and used to have code coverage working via nyc. But now I just get zeros across the board. I am using babel@7, if that needs custom config. Example repo:

https://github.com/gas-buddy/configured-swagger-client

**Comment by djMax** [comment] 2019-04-26 22:47
Got it. In package.json, I had this from the "old days"

```
    "sourceMap": false,
    "instrument": false,
```

Which has to go away it seems.

**Comment by djMax** [comment] 2019-04-27 12:20
This is a little more subtle. In some other projects, sourceMap: true fails, where sourceMap: false does not. Is this related to #527?

**Comment by isaacs** [comment] 2019-04-27 16:57
Does eslint find any problems with the files?  Does `use strict` cause them to fail?  If so, yes, likely related to #527.

Do you have an example where it is not working?  (I assume the fix you mentioned made it work for configured-swagger-client?)

**Comment by djMax** [comment] 2019-04-27 19:01
Yeah, I don't have it on a public project yet. Will try to isolate it. I do imagine it's related to "complex" code - the linter passes it (airbnb rules) but we use lots of transforms, optional chaining, etc.

**Comment by djMax** [comment] 2019-04-28 17:59
Confirmed that babel is adding use strict to everything, so it's not 527 I guess.

**Comment by smartiniOnGitHub** [comment] 2019-05-09 12:26
Hi all, since Tap 13 still I have some strange behavior on tests, I guess if it's related to the usage of 'use strict' even in my test files; the first run of test normal or coverage (in this project tests are trivial, ok) is good, but other run always fail, could be something related to eslint comments inside sources ?
The error is:
```
Cannot read property 'f' of undefined
```
whick points to the first line of my eslint comments in the source.

The example project is [here](https://github.com/smartiniOnGitHub/fastify-example), and test source is [sample.test.js](https://github.com/smartiniOnGitHub/fastify-example/blob/master/test/sample.test.js). 

Note that I had to remove the '--strict' flag from npm custom commands or Tap would not work, but it's not clear (reading the docs) if that flag is still valid.

Sorry, tell me if you prefer a different issue for problems I see.
Of course be free to ask me if you need more info. Thanks for the help.

**Comment by isaacs** [comment] 2019-05-09 16:49
@smartiniOnGitHub I think this might be a different issue.  Something is getting borked when `esm` reads the transpiled source from its cache.

You can make your tests pass by adding one of these options to your package.json file:

This will disable esm entirely:
```json
{
  "tap": {
    "esm": false
  }
}
```

This will make esm not use its cache:
```json
{
  "tap": {
    "test-env": [
      "ESM_DISABLE_CACHE=1"
    ]
  }
}
```

In either case, you probably want to remove the `node_modules/.cache/esm` folder just to ensure it's not causing problems.

cc: @jdalton

**Comment by smartiniOnGitHub** [comment] 2019-05-10 16:31
@isaacs Hi, thanks, by adding the '--no-esm' flag in my npm custom commands to run Tap all has been resolved. 
But trying to use '--strict' still doesn't work (is it still valid) ? Tell me if I should open a new issue for that.
Thanks a lot for the help and for this great Testing framework :-) . Bye

**Comment by isaacs** [comment] 2019-05-10 17:47
The `--strict` flag was a bug. It was expanding to pass `--strict` to  node, but the node arg is actually `--use-strict`.  Fixed in ce70c7b, and published as latest.

If you run into any other problems, yes, please do open a new issue.  Helps to keep things better organized that way :)

**Comment by smartiniOnGitHub** [comment] 2019-05-11 10:09
Perfect, thank you very much for now :-) .

**Comment by isaacs** [comment] 2019-07-03 22:52
This has gone a few months without an update, so I'm closing it.  Happy to reopen if there are any more details to dig into.

**Closed as completed by isaacs** 2019-07-03 22:52 UTC

**Comment by huan** [comment] 2021-09-01 05:42
I have run into this issue this week after we switch to ESM and it can be reproduced:

https://github.com/wechaty/wechaty/runs/3480428225?check_suite_focus=true#step:6:7

Adding `ESM_DISABLE_CACHE=1` to `package.json` seems can not fix the failure.
