### ISSUE TITLE
Command line option to require module

### ISSUE THREAD

**Issue by domachine** [tapjs/tapjs#221] opened 2016-01-28 13:21 UTC
Have you ever thought about an option that requires a module before running a test? This would be useful to use babel for example. The readme of tape [describes this](https://github.com/substack/tape/#preloading-modules). If this is of interest I'd happily prepare a pull-request.

**Comment by jamestalmage** [comment] 2016-01-28 21:47
I think it is a good idea. 

FYI: `nyc` can actually already handle this for you.

**Comment by isaacs** [comment] 2016-01-28 21:54
In the latest version of node-tap, you can do `--node-arg=-r --node-arg=/path/to/babel`, I believe, to have node load babel for you.  (This `-r` arg to node only works in relatively recent node versions, iirc.)  You can also pass nyc args in a similar way: `--nyc-arg=--some-key --nyc-arg=some-value`

I'm going to close this issue, since it's already something you can do.  However!  I'd _love_ a documentation patch that explains how to do this, and if for some reason I've misunderstood your request and this doesn't work out, please let me know and we can re-open.

**Closed as completed by isaacs** 2016-01-28 21:54 UTC

**Comment by jamestalmage** [comment] 2016-01-28 22:26
`nyc` makes it a bit simpler (and it works on old node as well).  Just do:

```
$ nyc --require=babel-core/register tap
```

The [implementation is pretty simple](https://github.com/bcoe/nyc/blob/master/index.js#L101-L114). I think it has value for `node-tap` as well.

**Comment by isaacs** [comment] 2016-01-29 01:44
Right, but that only works if you're using coverage.  From tap, this could be:

```
tap test/*.js --cov --nyc-arg=--require=babel-core/register
```

In either event, not something that needs any new work on this module :)

**Comment by jamestalmage** [comment] 2016-01-29 01:54
Unless they are using Node `0.12` (or using `tap` to test a product they want to support in Node `0.12`).

**Comment by isaacs** [comment] 2016-01-29 02:03
Right.  There are options :)  Do you know when `-r` was added?

**Comment by jamestalmage** [comment] 2016-01-29 02:11
It doesn't work in `0.12.7`, it does work in `4.0.0`. That's all I know :smile:

**Comment by domachine** [comment] 2016-01-29 08:01
Cool. Didn't even know that the `-r` option exists in node. Thx for the hint.

**Comment by pke** [comment] 2017-11-26 22:04
@isaacs I can't get the `tap test/*.js --nyc-arg=--require=babel-core/register` to work with `faucet`
I tried `tap test/*.js --nyc-arg=--require=babel-core/register | faucet` but it throws 

```tty
(function (exports, require, module, __filename, __dirname) { import t from "tap"
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
```

**Comment by isaacs** [comment] 2017-11-26 22:27
@pke `--nyc-arg` is only relevant if you're enabling code coverage.  So, either add `--cov` onto that, or use `--node-arg` instead.

**Comment by pke** [comment] 2017-11-27 13:10
Not sure how `--node-arg` would help to output the spec with `faucet`. After all the normal call would be: `tap ... | faucet`. How does this work with `nyc`? @isaacs

**Comment by isaacs** [comment] 2017-11-27 17:47
@pke The problem isn't faucet, it's running the tests at all.  You'll note that it fails the exact same way if you leave off the `| faucet` bit.  You're passing the `--require` argument to nyc, but you're not using nyc, so `--nyc-arg` has no effect.  You need to use `--node-arg` instead, or enable coverage with `--cov`.

**Comment by pke** [comment] 2017-12-03 00:56
Sorry to hijack this issue again, but I think it fits here and does not justify opening a new issue:

I have those tasks:

```
"scripts": { 
"cov": "cross-env NODE_ENV=test nyc tap -r spec --color src/**/*.spec.js",
"cov1": "cross-env NODE_ENV=test nyc tap -r spec --color ",
"tap": "npm run tap1 src/**/*.spec.js",
"tap1": "cross-env NODE_ENV=test TAP_RCFILE=./.taprc tap",
}
"nyc": {
    "cache": true,
    "require": [
      "./spec/setup"
    ],
    "exclude": [
      "spec/*.js",
      "**/*.spec.js"
    ],
    "sourceMap": false,
    "instrument": false
}
```

And this `.taprc` file:

```
{
   "nodeArgs": [
    "--require",
    "./spec/setup"
  ],
  "nycArgs": [
    "--require=./spec/setup"
  ],
  "timeout": 30,
  "color": true,
  "reporter": "spec"
}
``` 

I could already simplify the `tap` task to just call `tap1` with a globbing spec.

However the same does not seem to work with my `cov` task. When it calls `cov1` (and using the same .taprc file), then I can again see dreaded `SyntaxError: Unexpected token import` error. The same happens when I want to use the .taprc file for the `cov` task.
The same happens when I call `npm run tap1 --cov specs/spec1.js`
I seem to be still confused when `node-arg` and `nyc-arg` are used and when does what have precedence ( also with the nyc entry in the package.json)

`./spec/setup`
```
require("babel-register")
require("./enzyme")
```
