### ISSUE TITLE
[BUG] test run failing only on windows

### ISSUE THREAD

**Issue by sinedied** [tapjs/tapjs#954] opened 2023-10-10 07:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

After updating to latest tap version (18.4.5), my tests have started to fail on Windows. It's still working fine on Linux and MacOS.

See pipeline here: https://github.com/Azure-Samples/azure-search-openai-javascript/actions/runs/6458397288/job/17532021565?pr=64

Relevant logs
```
npm test
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"

> azure-search-openai-javascript@1.0.0 test
> npm run test -ws --if-present


> indexer@1.0.0 test
> tsc -p test/tsconfig.json && tap --allow-incomplete-coverage "test-dist/**/*.test.js"

D:\a\azure-search-openai-javascript\azure-search-openai-javascript\node_modules\.bin\generate-tap-test-class:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at internalCompileFunction (node:internal/vm:7[3](https://github.com/Azure-Samples/azure-search-openai-javascript/actions/runs/6459486148/job/17535337279#step:9:3):18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .js] (D:\a\azure-search-openai-javascript\azure-search-openai-javascript\packages\indexer\node_modules\ts-node\src\index.ts:1608:[4](https://github.com/Azure-Samples/azure-search-openai-javascript/actions/runs/6459486148/job/17535337279#step:9:5)3)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:2[5](https://github.com/Azure-Samples/azure-search-openai-javascript/actions/runs/6459486148/job/17535337279#step:9:6))
D:\a\azure-search-openai-javascript\azure-search-openai-javascript\node_modules\@tapjs\run\src\build.ts:31
          Object.assign(new Error('build failed'), {
                        ^


Error: build failed
    at <anonymous> (D:\a\azure-search-openai-javascript\azure-search-openai-javascript\node_modules\@tapjs\run\src\build.ts:31:25)
    at ChildProcess.<anonymous> (D:\a\azure-search-openai-javascript\azure-search-openai-javascript\node_modules\foreground-child\src\index.ts:1[6](https://github.com/Azure-Samples/azure-search-openai-javascript/actions/runs/6459486148/job/17535337279#step:9:7)3:20)
    at ChildProcess.emit (node:events:51[7](https://github.com/Azure-Samples/azure-search-openai-javascript/actions/runs/6459486148/job/17535337279#step:9:8):2[8](https://github.com/Azure-Samples/azure-search-openai-javascript/actions/runs/6459486148/job/17535337279#step:9:9))
    at cp.emit (D:\a\azure-search-openai-javascript\azure-search-openai-javascript\node_modules\cross-spawn\lib\enoent.js:34:2[9](https://github.com/Azure-Samples/azure-search-openai-javascript/actions/runs/6459486148/job/17535337279#step:9:10))
    at maybeClose (node:internal/child_process:[10](https://github.com/Azure-Samples/azure-search-openai-javascript/actions/runs/6459486148/job/17535337279#step:9:11)98:[16](https://github.com/Azure-Samples/azure-search-openai-javascript/actions/runs/6459486148/job/17535337279#step:9:17))
    at ChildProcess._handle.onexit (node:internal/child_process:303:5) {
  code: 1,
  signal: null
}

Node.js v[18](https://github.com/Azure-Samples/azure-search-openai-javascript/actions/runs/6459486148/job/17535337279#step:9:19).18.0
npm ERR! Lifecycle script `test` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: indexer@1.0.0 
npm ERR!   at location: D:\a\azure-search-openai-javascript\azure-search-openai-javascript\packages\indexer
```

### Reproduction

You can checkout this branch https://github.com/Azure-Samples/azure-search-openai-javascript/tree/tests
and run `npm test` on Windows.

### Environment

I do not have a Windows environment at hand, only the GH Actions worker so I ran the commands in my regular dev environment and paster the Windows version from the GH logs.

```
which tap
npm ls tap
azure-search-openai-javascript@1.0.0 /workspaces/azure-search-open-ai-javascript
├─┬ indexer@1.0.0 -> ./packages/indexer
│ └── tap@18.4.5
└─┬ search@1.0.0 -> ./packages/search
  └── tap@18.4.5 deduped
npx tap versions
tap: 18.4.5
"@tapjs/config": 2.4.5
"@tapjs/core": 1.3.9
"@tapjs/run": 1.4.5
"@tapjs/stack": 1.2.5
"@tapjs/test": 1.3.9
tap-parser: 15.2.0
tap-yaml: 2.2.0
tcompare: 6.4.2
plugins:
  "@tapjs/after": 1.1.9
  "@tapjs/after-each": 1.1.9
  "@tapjs/asserts": 1.1.9
  "@tapjs/before": 1.1.9
  "@tapjs/before-each": 1.1.9
  "@tapjs/filter": 1.2.9
  "@tapjs/fixture": 1.2.9
  "@tapjs/intercept": 1.2.9
  "@tapjs/mock": 1.2.7
  "@tapjs/node-serialize": 1.1.9
  "@tapjs/snapshot": 1.2.9
  "@tapjs/spawn": 1.1.9
  "@tapjs/stdin": 1.1.9
  "@tapjs/typescript": 1.2.9
  "@tapjs/worker": 1.1.9
npx tap config list
npx tap plugin list
# vim: set filetype=yaml :
color: true
coverage-report:
  - text
exclude:
  - "**/@(fixture*(s)|dist)/**"
include:
  - "**/@(test?(s)|__test?(s)__)/**/*.@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/*.@(test?(s)|spec).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/test?(s).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
jobs: 1
reporter: base
snapshot-clean-cwd: true
timeout: 30
@tapjs/after
@tapjs/after-each
@tapjs/asserts
@tapjs/before
@tapjs/before-each
@tapjs/filter
@tapjs/fixture
@tapjs/intercept
@tapjs/mock
@tapjs/node-serialize
@tapjs/snapshot
@tapjs/spawn
@tapjs/stdin
@tapjs/typescript
@tapjs/worker
# if using typescript:
npm ls ts-node
azure-search-openai-javascript@1.0.0 /workspaces/azure-search-open-ai-javascript
├─┬ @tapjs/nock@3.1.9
│ └─┬ @tapjs/core@1.3.9
│   └─┬ @tapjs/test@1.3.9
│     └── ts-node@npm:@isaacs/ts-node-temp-fork-for-pr-2009@10.9.1
├─┬ indexer@1.0.0 -> ./packages/indexer
│ ├─┬ tap@18.4.5
│ │ └─┬ @tapjs/typescript@1.2.9
│ │   └── ts-node@npm:@isaacs/ts-node-temp-fork-for-pr-2009@10.9.1 deduped
│ └── ts-node@10.9.1
└─┬ search@1.0.0 -> ./packages/search
  └── ts-node@10.9.1

npm ls tsc

azure-search-openai-javascript@1.0.0 /workspaces/azure-search-open-ai-javascript
└── (empty)

# windows (in powershell)
"$([Environment]::OSVersion.VersionString) $(('x86', 'x64')[[Environment]::Is64BitOperatingSystem])"
Microsoft Windows Server 2022
  10.0.20348
```

**Comment by isaacs** [comment] 2023-10-10 14:02
I see what's going on. Will be fixed in the next few hours on 18.4.6

**Closed as completed** 2023-10-10 14:01 UTC
Labels: bug

**Comment by sinedied** [comment] 2023-10-11 16:22
Thanks! I just tried the latest version, but now it seems that other builds were affected, ie the MacOS build now fails:

https://github.com/Azure-Samples/azure-search-openai-javascript/actions/runs/6485252454/job/17610927132?pr=64

```
> indexer@1.0.0 test
> tsc -p test/tsconfig.json && tap --allow-incomplete-coverage "test-dist/**/*.test.js"

node:internal/process/esm_loader:[10](https://github.com/Azure-Samples/azure-search-openai-javascript/actions/runs/6485252454/job/17610927132?pr=64#step:9:11)8
    internalBinding('errors').triggerUncaughtException(
                              ^

[Error: Package subpath './generate-tap-test-class' is not defined by "exports" in /Users/runner/work/azure-search-openai-javascript/azure-search-openai-javascript/node_modules/@tapjs/test/package.json imported from /Users/runner/work/azure-search-openai-javascript/azure-search-openai-javascript/packages/indexer/x] {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v18.18.0
npm ERR! Lifecycle script `test` failed with error: 
npm ERR! Error: command failed 

npm ERR!   in workspace: indexer@1.0.0 
> search@1.0.0 test
npm ERR!   at location: /Users/runner/work/azure-search-openai-javascript/azure-search-openai-javascript/packages/indexer 
> tsc -p test/tsconfig.json && tap --allow-incomplete-coverage "test-dist/**/*.test.js"

node:internal/process/esm_loader:108
    internalBinding('errors').triggerUncaughtException(
                              ^

[Error: Package subpath './generate-tap-test-class' is not defined by "exports" in /Users/runner/work/azure-search-openai-javascript/azure-search-openai-javascript/node_modules/@tapjs/test/package.json imported from /Users/runner/work/azure-search-openai-javascript/azure-search-openai-javascript/packages/search/x] {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v[18](https://github.com/Azure-Samples/azure-search-openai-javascript/actions/runs/6485252454/job/17610927132?pr=64#step:9:19).18.0
npm ERR! Lifecycle script `test` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: search@1.0.0 
npm ERR!   at location: /Users/runner/work/azure-search-openai-javascript/azure-search-openai-javascript/packages/search 
Error: Process completed with exit code 1.
```

**Comment by isaacs** [comment] 2023-10-11 20:58
@sinedied Love a publicly visible bug that I can just pull and repro.

The issue is that you have multiple copies of @tapjs/core because you updated tap, but not @tapjs/nock

There's a lot of ways to do things, but I recommend making all your tooling stuff like test runners and linters deps in the root of the project, rather than within each workspace. Helps immensely with keeping the monorepo consistent, and avoids duplication weirdnesses like this.

It'd probably be good to loosen the peerDep for the optional plugins, and perhaps move them out of the monorepo so that they're not so tightly bound to a given @tapjs/core version, which would not only have avoided this problem, but will also make tap's builds and publishes way faster.

**Comment by sinedied** [comment] 2023-10-11 22:05
Thanks for taking time looking into this, it's really appreciated.
You're right about putting tooling at the root of the workspace, I'll probably do that as it makes the maintenance easier and less error prone.

**Comment by sinedied** [comment] 2023-10-13 10:07
Just sent you a small token of appreciation for all the time you've taken with my issues.
I know it's not much but at least you can grab a good cup of coffee or beer on my behalf 🙂

**Comment by isaacs** [comment] 2023-10-14 06:05
Thanks! ☺️
