### ISSUE TITLE
separating flags and filenames with -- doesn't seem to work anymore

### ISSUE THREAD

**Issue by toddself** [tapjs/tapjs#209] opened 2016-01-04 23:10 UTC
Our test command has been: `tap --cov --coverage-report=lcov -- [files]` for a while.

Updated to version 5 today and am getting the following behavior:

```
scripto@scripto:/mnt/nfs/src/scripto2$ time node_modules/.bin/tap --cov --coverage-report=lcov -- src/test/server/*.spec.js src/test/server/*.integration.js

real    0m2.217s
user    0m1.704s
sys 0m0.132s
scripto@scripto:/mnt/nfs/src/scripto2$
```

(Our full test suite is about ~7-8 minutes to run)

If I remove the `--` between `lcov` and the filenames it works again though.

**Comment by isaacs** [comment] 2016-01-04 23:56
How very interesting!

I can't reproduce.  What version of tap are you using?  `npm ls tap` will show you.

**Comment by isaacs** [comment] 2016-01-05 02:45
Oh, you said in the OP, "updated to version 5".

What OS?  Is it possible that the first file is bailing in some tragic way?  Can you add `-Rtap` to the command to see what it's outputting?

**Comment by toddself** [comment] 2016-01-05 03:45
Sorry for the delay had to get the kids fed and in bed!

Yes I just upgraded to tap 5:

```
todd@scripto:/mnt/nfs/src/scripto2$ npm ls tap
scripto@1.0.0 /mnt/nfs/src/scripto2
└── tap@5.0.0
```

I thought it might be bailing in some tragic failure in the first test but removing the `--` allows the test to run to completion. Your suggestion for the `-Rtap` however produces a stack trace.

```
todd@scripto:/mnt/nfs/src/scripto2$ node_modules/.bin/tap --cov --coverage-report=lcov -Rtap -- src/test/server/*.spec.js

/mnt/nfs/src/scripto2/node_modules/tap/node_modules/nyc/node_modules/istanbul/node_modules/esprima/esprima.js:5703
            throw e;
            ^
Error: Line 2: Unexpected token ;
    at constructError (/mnt/nfs/src/scripto2/node_modules/tap/node_modules/nyc/node_modules/istanbul/node_modules/esprima/esprima.js:2405:21)
    at createError (/mnt/nfs/src/scripto2/node_modules/tap/node_modules/nyc/node_modules/istanbul/node_modules/esprima/esprima.js:2424:17)
    at unexpectedTokenError (/mnt/nfs/src/scripto2/node_modules/tap/node_modules/nyc/node_modules/istanbul/node_modules/esprima/esprima.js:2498:13)
    at throwUnexpectedToken (/mnt/nfs/src/scripto2/node_modules/tap/node_modules/nyc/node_modules/istanbul/node_modules/esprima/esprima.js:2503:15)
    at expect (/mnt/nfs/src/scripto2/node_modules/tap/node_modules/nyc/node_modules/istanbul/node_modules/esprima/esprima.js:2521:13)
    at expectCommaSeparator (/mnt/nfs/src/scripto2/node_modules/tap/node_modules/nyc/node_modules/istanbul/node_modules/esprima/esprima.js:2545:13)
    at parseArguments (/mnt/nfs/src/scripto2/node_modules/tap/node_modules/nyc/node_modules/istanbul/node_modules/esprima/esprima.js:3331:17)
    at parseLeftHandSideExpressionAllowCall (/mnt/nfs/src/scripto2/node_modules/tap/node_modules/nyc/node_modules/istanbul/node_modules/esprima/esprima.js:3424:24)
    at inheritCoverGrammar (/mnt/nfs/src/scripto2/node_modules/tap/node_modules/nyc/node_modules/istanbul/node_modules/esprima/esprima.js:2679:18)
    at parsePostfixExpression (/mnt/nfs/src/scripto2/node_modules/tap/node_modules/nyc/node_modules/istanbul/node_modules/esprima/esprima.js:3488:16)
todd@scripto:/mnt/nfs/src/scripto2$
```

However, whenever I try to use `-Rtap` in this project (even without the `--`) it fails with that above stacktrace.

If I run without `-Rtap` and `--` it works just fine:

```
todd@scripto:/mnt/nfs/src/scripto2$ LOG_LEVEL=none node_modules/.bin/tap --cov --coverage-report=lcov src/test/server/*.spec.js
src/test/server/app.spec.js ........................... 3/4 1s
  Skipped: 1
    shows list of printers

src/test/server/backup_new.spec.js ................ 115/115
src/test/server/backup.spec.js .................... 115/115
src/test/server/datafiles.spec.js ..................... 4/4 2s
src/test/server/db-postgres.spec.js ............... 100/100
src/test/server/db.spec.js ........................ 100/100
src/test/server/folder-messages.spec.js ........... 100/100
src/test/server/formatter.spec.js ................... 16/16
src/test/server/printgrid.spec.js ..................... 4/4 7s
src/test/server/rundown-messages.spec.js ............ 70/70
src/test/server/scripttopdf.spec.js ................... 4/4 2s
src/test/server/settings.spec.js ...................... 9/9
src/test/server/specialpages.spec.js ................ 73/73
src/test/server/split-columns.spec.js ................. 7/7
src/test/server/users.spec.js ....................... 23/23 7s
total ............................................. 743/744

  743 passing (2m)
  1 pending
todd@scripto:/mnt/nfs/src/scripto2$
```

Let me try to run each spec file individually with tap and see if one of them in specific is causing the issue.

**Comment by toddself** [comment] 2016-01-05 04:00
Every single file in our test suite causes the stacktrace to throw on `-Rtap`. It's hard to figure out what is causing the error to throw (we are in the midst of upgrading to standard so some of our files have semi-colons, some don't -- it throws regardless) if I run each one individually.  If I run each one with no reporter specified, the tests complete.

This is being run on Ubuntu 12.04, node 4.2.4, npm 2.14.12.  It is being run on an NFS mounted file-system exported from my Mac (Ubuntu is running via xhyve in the native hypervisor)

**Comment by toddself** [comment] 2016-01-05 04:06
OK!  So thinking about this I tried to run this on a fresh npm install not on the NFS mount.

The good news is that `-Rtap` no longer gives me a stacktrace. That might be an odd modules issue?  IDK.  However, it provides no output anymore:

```
todd@scripto:~/src/scripto2$ node_modules/.bin/tap --cov --coverage-report=lcov -Rtap -- src/test/server/*.spec.js
todd@scripto:~/src/scripto2$ node_modules/.bin/tap --cov --coverage-report=lcov -- src/test/server/*.spec.js
```

Removing `--` does allow the tests (and the tap reporter) to run.

**Comment by isaacs** [comment] 2016-01-05 06:53
I don't suppose this code is public somewhere I could take a look at?

Does it work on a fs that isn't Nfs mounted? Eg, git checkout into another path or something?

**Comment by toddself** [comment] 2016-01-05 18:58
Yeah it fails on the local FS.  I'm working on making a smaller reproducible test case without all the cruft of our main rep.

Thanks for the attention to this issue.

**Comment by isaacs** [comment] 2016-01-05 23:31
That stack trace looks like esprima is borking on something in your code.  That's probably a bug in esprima, but it's being triggered by something specific in your code somewhere.  (Most likely a file that every test loads?)

I'm still confused about why the `--` would have any effect.

If you manage to pare it down to a minimal(-ish) test case, I'm eager to poke at it.

**Comment by isaacs** [comment] 2016-02-22 04:27
Closing because I can't reproduce.  Happy to re-open if this is still a problem and a reproduction case can be found.

**Closed as completed by isaacs** 2016-02-22 04:27 UTC
