### ISSUE TITLE
Interop with node.js test runner

### ISSUE THREAD

**Issue by rotu** [tapjs/tapjs#888] opened 2023-09-15 05:15 UTC
Running tests with the [Node.js test runner](https://nodejs.org/api/test.html#running-tests-from-the-command-line) `node --test` seems to simply run all tap files.

In particular `node --test --test-name-pattern="no test matches this"` simply runs all files as simple scripts, without any filtering on the pattern.

To what extent is the Node.js test runner supported (is this planned? Does a plugin exist?)

**Comment by isaacs** [comment] 2023-09-15 18:27
It's funny you mention that, I was just writing up an example to look into this.  I'll have a demo repo up shortly.

I haven't yet dug into exactly how it communicates the filters and how it parses the output, but it's definitely doing more than just parsing TAP on stdout, because it seems to just dump the TAP output to stdout if it's not using `node:test`, but tally up suite and test counts if it is.

Running `node:test` style tests with the `tap` runner works fine, but for example `tap --grep 'pattern' blah.test.js` won't filter `node:test` tests, because `node:test` doesn't use the `TAP_GREP` environment variable as its source of filter patterns.

For simple use cases, you can definitely use the tap runner with `node:test` tests, though, because they do output TAP on stdout when run with a non-TTY stdout.

@cjihrig ping, any pointers you can provide about `node:test` inner workings and/or how 3rd party runners can hook into `node:test` tests or 3rd party frameworks can interop with `node --test`?

**Comment by cjihrig** [comment] 2023-09-15 19:07
Thanks for the ping.

> how 3rd party runners can hook into node:test tests

So if the TAP runner wants to run a file or files that use `node:test`, that should work. Each test file is a "normal" Node program that outputs the results in whatever format(s) the reporter(s) are configured to use. However, if you use the `--test` flag, then each test file runs as a child process that sends its results back to the main test runner process using V8 serialization (this used to use TAP as well, but was changed to simplify things and remove the TAP parser from core).

If for whatever reason the runner is not receiving TAP on stdout, you can look into using the [`NODE_TEST_CONTEXT=child`](https://nodejs.org/api/cli.html#node_test_contextvalue) environment variable or the [`--test-reporter`](https://nodejs.org/api/cli.html#--test-reporter) and [`--test-reporter-destination`](https://nodejs.org/api/cli.html#--test-reporter-destination) CLI flags

If you want to hook into the output in a more programmatic fashion, you could use the [reporters API](https://nodejs.org/api/test.html#test-reporters).

> 3rd party frameworks can interop with node --test

That might be trickier. As I mentioned, the internal serialization is now done via [V8 serialization](https://github.com/nodejs/node/blob/main/lib/internal/test_runner/reporter/v8-serializer.js). But if you could mimic that output, it should also work.

> I haven't yet dug into exactly how it communicates the filters and how it parses the output

If using the CLI runner (`--test`), the CLI arguments are passed directly to the child processes, with a bit of [filtering applied](https://github.com/nodejs/node/blob/6a489df73b0ab64f8fab016a7a71e209066fdb82/lib/internal/test_runner/runner.js#L108). In each test file, the patterns [are applied here](https://github.com/nodejs/node/blob/6a489df73b0ab64f8fab016a7a71e209066fdb82/lib/internal/test_runner/test.js#L291). I don't know a ton about how `TAP_GREP`, but you might be able to convert it to patterns that `node:test` supports and then start the child processes with those patterns passed as `--node-test-pattern` values.

**Comment by isaacs** [comment] 2023-09-15 19:26
At present, `tap` running the `node:test` tests is pretty nice, but could be improved.  `node --test` running the tap tests is noisy af, but does report pass/fail correctly at least.

### Filtering

> I don't know a ton about how TAP_GREP, but you might be able to convert it to patterns that node:test supports and then start the child processes with those patterns passed as --node-test-pattern values.

`env.TAP_GREP` is what the tap framework sees when you start the runner with `tap --grep <whatever>`, or put `"grep": ["pattern"]` in a tap config file. All configs -> envs for consumption.

It seems like I can have the `@tapjs/filter` plugin turn that env into a `--node-test-pattern=<whatever>` in the NODE_OPTIONS env or add it to the child process command line, and it should Just Work?

### reporting: tap runner, node:test used in the test

Yes, the tap cli is getting TAP output by the `node:test` child procs, so that's fine. The data isn't quite in the same shape that node-tap expects it, but it's valid TAP, so it's not too bad.

How stable is the yaml diagnostic data? I could certainly adjust things to consume it a bit more gracefully. Right now the reporter is basically just printing it out as-is, which is not terrible, but could be better.

(It would be nice if `node:test` output `# time=...` rather than a `duration_ms` diagnostic or comment, but that suggestion in the TAP spec discussion never really went anywhere, and I can certainly consume `duration_ms` easily enough.)

### reporting: node --test, tap used in test

I'll take a look at the reporter API and v8 serialization links you provided, thanks!

**Comment by isaacs** [comment] 2023-09-15 19:27
The example repo is here: https://github.com/tapjs/node-test-example/tree/main

**Comment by cjihrig** [comment] 2023-09-15 19:51
> It seems like I can have the @tapjs/filter plugin turn that env into a --node-test-pattern=<whatever> in the NODE_OPTIONS env or add it to the child process command line, and it should Just Work?

I believe so, but also famous last words.

> How stable is the yaml diagnostic data?

I think it's pretty stable.

> It would be nice if node:test output # time=... rather than a duration_ms diagnostic or comment

I originally went with `duration_ms` because that's what Node's tooling was already using. I would [prefer having it as part of the spec too](https://github.com/TestAnything/Specification/issues/16#issuecomment-1366802832) 😄.

**Comment by isaacs** [comment] 2023-09-17 20:08
Ok, looking into this a bit more:

- I don't think it's worth doing _much_ special for `tap` + `node:test`. Node's `node:test` is already emitting TAP by default, I just need to make it somewhat savvy about the diagnostic naming conventions, but that's pretty straightforward.
- Getting `import 'tap'` tests to play nicer with `node --test` will involve:
  - detect "output in serialized mode" state when `NODE_TEST_CONTEXT=child-v8`
  - work out the object types that node expects to see in the serialized result
  - run that through the v8.DefaultSerializer
  - write to stdout

Unless you can show me a doc I've missed documenting each of the objects, I'm looking at RTFS, empirical testing, and hacking node to tell it to dump the data out unserialized. (That's not horrible, kinda fun actually, and sometimes still needed because docs are never 100%, but types and semantic intentions would be a shortcut. It _looks_ like they correspond to events that the test reporters API exposes, and are defined in `lib/internal/test_runner/tests_stream.js`, yes?)

The one downside there will be that tap's runner captures quite a lot from the TAP output, which it looks like isn't captured in the node:test serialization, but no sense giving it more if it isn't going to do anything with it anyway.

**Comment by rotu** [comment] 2023-09-17 23:44
Although often a dead end, [TFM looks pretty great here](https://nodejs.org/api/test.html#class-testsstream)!

**Comment by isaacs** [comment] 2023-09-18 00:39
@rotu Thank you! that's what I was looking for, but finding something that was much less exhaustive. I knew it was probably in there somewhere.

**Comment by isaacs** [comment] 2023-09-18 04:05
Notes, some of these will become other issues in a moment:

## Running `node:test` tests with the `tap` runner

### Interpreting `node:test`'s TAP

From `node:test` tap output to node-tap's yaml conventions:

- `duration_ms: <number>` diag -> `# time=<number>ms` directive
- `# duration_ms <number>` comment -> `# time=<number>ms` comment
- errors:
    - diag object with: `{ error: string, type: string, stack?:
      string, code?: string }`, and typically `{ failureType:
      'testCodeFailure' | 'subtestsFailed' }`.
    - `error` -> becomes `message`
    - `stack` -> parse and prettify wth `@tapjs/stack`. It does
      _not_ have a `message` header as the first line. (Tap
      handles both anyway, out of necessity, so it wouldn't
      matter much if it did.)
    - `location` -> a `file:line:col` string roughly
      corresponding to tap's `at` field.

We can get the `at` from `location` if present, else the stack.

### Tap args and `NODE_OPTIONS`

It really looks like plugins should have a way to add stuff to
the `node-arg` config.

This is a bit weird, because they're really not _supposed_ to
modify config stuff, but there's nothing stopping a plugin from
touching it.

But, maybe the TAP class could have a `nodeArg` property, set to
the delimited `TAP_NODE_ARG` env config initially, and then a
plugin could add to the array at init time and the runner could
pull it off of that?

- `--grep` -> `--test-name-pattern` Cannot be set in
  `NODE_OPTIONS`. It _must_ be set in the test args.
- `--only` -> `--test-only` Can be set in `NODE_OPTIONS`, so if
  `env.TAP_ONLY==='1'`, then `env.NODE_OPTIONS+=' --test-only'`
  and that's done.

## Serialization

Output serialization events instead of `TAP` when
`env.NODE_TEST_CONTEXT=child-v8`.

All the objects are serialized with `{ type, data }`.

`data.file` is always the `t.options.at.fileName` if found, or
`undefined` if the repl or something else.

- `test:dequeue` emit for tap's `subtestStart` event. Data is
  `{name: string, file: string, nesting: number}`. `file`,
  `line`, and `column` come from `t.options.at`, nesting is the
  _parent_ nesting level, with children of the root TAP object
  being nesting level `0`. (No event emitted for root TAP object,
  because it has no parent to emit `subtestStart`.)
- `test:diagnostic` emit for TAP comments. `{file:string,
  message: string, nesting: number }`. `file`, `line`, and
  `column` come from `t.options.at`. It looks like `t.diagnostic`
  comments are printed in the parent after the test ends, so
  again `nestingLevel` applies to the parent. `t.diagnostic()` is
  a bit like `t.after(() => t.comment(msg))`, printing on the
  parent after the test ends.
- `test:enqueue` emit for tap's `subtestAdd` event.
  `{name:string,file:string,nesting:number}` same semantics as
  `test:dequeue`.
- `test:plan` not the actual plan, since `node:test` only expects
  test points for _subtests_, not _assertions_. This is always a
  trailing value, there is no `t.plan()` in `node:test`. Options:
    - emit this serialized event for suites, but not assertions
    - emit `test:enqueue`/`test:dequeue`/`test:pass`/`test:fail`
      for all _assertions_ as well. This is likely to be very
      noisy, especially if the `node --test` harness is
      outputting TAP itself.
- `test:start` emit immediately after `test:dequeue`, with the
  same data.
- `test:stdout` any writes to stdout. `{file, message:string}`
- `test:stdout` any writes to stderr. `{file, message:string}`
- `test:pass` Emitted when a subtest emits `complete` with
  a FinalResults (not just any passing assertion).
- `test:fail` Same as `test:pass`, but if it's failing.

Pass/fail data:

- `details`
    - `duration_ms` what node-tap calls `# time=...`, but always
      in ms.
    - `type` set to `'suite'` if created with `describe()`.
      Literally no other difference that I can tell. Probably
      tap should just set this if the test had any subtests?
    - `error` for `test:fail`, this is an Error object describing
      the failure. See below.
- `file`, `line`, and `column` come from `t.options.at`.
- `name` the name of the test that's finished
- `nesting` the nesting level of the _parent_ test. (not emitted
  for the root TAP test.)
- 

### Failure `details.error`

Node only fails tests by throwing an error. Tap can have 1 or
more failed test points, _or_ a thrown error.

If we throw an error, that's easy, there's 1 failed test point,
and it's error shaped.

If we get multiples what to do? Just serialize the first one as
the error cause?

Error message is always `'[Error [ERR_TEST_FAILURE]: ${failed
test point message}]'`, with a `code: 'ERR_TEST_FAILURE'` and a
`failureType` of `'subtestsFailed'` if caused by a subtest, or
`'testCodeFailure'` if it failed locally.

The `cause` property is set to whatever triggered the failure. In
the case of a thrown error, it's the error that was thrown, but
it can also be any value.

Since failed test points typically have a `stack`, we can
probably create an Error object for each one, and then have
something like, `Object.assign(new Error('7 test points failed'),
{ cause: this.lists.fail })` or something, presenting an array of
data objects pointing to the sources. If there's only one test
point, create an `Error` for it, with the appropriate message and
stack, and serialize that as the `cause` property.

Any other diagnostics that aren't captured in the error (ie,
anything but `cause`, `message`, and `stack`) can be attached as
additional properties, these are displayed.

**Comment by cjihrig** [comment] 2023-09-18 12:10
> `file` always `mainScript`

This was actually a bug that will be fixed in the 20.7.0 release of Node. https://github.com/nodejs/node/commit/4e61c22699066f7581af24a9d51d64c7ec1026ff specifically will add the correct filename (normally the `mainScript` is the correct value, but there are possible edge cases where it is not), as well as the line and column of all tests.

**Comment by isaacs** [comment] 2023-09-18 21:59
@cjihrig In what cases will it not be the main script? Is it supposed to be the location where the error was raised? It looks like it's the location of the test file. But I guess it could be different if one test imports another?

**Comment by isaacs** [comment] 2023-09-18 22:01
Ah, yes, I see, just read through the commit message. In tap's lingo, this is the CallSiteLike `t.options.at`, we can generate the `location` from that as well.  (Updating comment above.)

**Comment by isaacs** [comment] 2023-09-19 02:36
Starting to come together :)

<img width="696" alt="Screenshot 2023-09-18 at 19 35 51" src="https://github.com/tapjs/tapjs/assets/9287/9dd7679b-98f8-4557-9654-7fa7c2ed54da">

**Closed as completed** 2023-09-22 17:20 UTC
