### ISSUE TITLE
getValidSourceFile during tap's typescript-compilation

### ISSUE THREAD

**Issue by rgrannell1** [tapjs/tapjs#688] opened 2020-07-26 20:46 UTC
Firstly, I love this library and use it frequently with JS projects. This is my first attempt to use it with TypeScript and unfortunately it hasn't worked.

Is there some configuration / option I can change to fix this error?

**Relevant Data:**

`package.json` has the field `"type": "module"` set due to difficulties with TypeScript compilation

**error-stack**
```
test/test-storage.ts 2> 
test/test-storage.ts 2> /home/rg/Code/poly/node_modules/typescript/lib/typescript.js:139175
test/test-storage.ts 2>                 var error = new Error("Could not find source file: '" + fileName + "'.");
test/test-storage.ts 2>                             ^
test/test-storage.ts 2> Error: Could not find source file: '/home/rg/.node-spawn-wrap-96303-a6de49eca932/node'.
test/test-storage.ts 2>     at getValidSourceFile (/home/rg/Code/poly/node_modules/typescript/lib/typescript.js:139175:29)
test/test-storage.ts 2>     at Object.getEmitOutput (/home/rg/Code/poly/node_modules/typescript/lib/typescript.js:139560:30)
test/test-storage.ts 2>     at getOutput (/home/rg/Code/poly/node_modules/ts-node/src/index.ts:562:32)
test/test-storage.ts 2>     at Object.compile (/home/rg/Code/poly/node_modules/ts-node/src/index.ts:775:32)
test/test-storage.ts 2>     at Module.m._compile (/home/rg/Code/poly/node_modules/ts-node/src/index.ts:858:43)
test/test-storage.ts 2>     at Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
test/test-storage.ts 2>     at Object.require.extensions.<computed> [as .js] (/home/rg/Code/poly/node_modules/ts-node/src/index.ts:861:12)
test/test-storage.ts 2>     at Module.load (internal/modules/cjs/loader.js:1085:32)
test/test-storage.ts 2>     at Function.Module._load (internal/modules/cjs/loader.js:950:14)
test/test-storage.ts 2>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
```

**steps to replicate**
```sh
git clone git@github.com:rgrannell1/poly2020.git
git checkout a05be7
npx tap test --no-esm
```

**tsconfig.json**

```json
{
  "compilerOptions": {
    "allowJs": true,
    "moduleResolution": "node",
    "module": "ESNext",
    "outDir": "out",
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": true,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "target": "ESNext"
  },
  "exclude": [
    "node_modules",
    "out"
  ]
}
```

**Comment by FauxFaux** [comment] 2020-10-18 21:36
While I don't know how to fix this (yet!), I do know it is caused by the coverage support. `tap --no-coverage` does not have the same problem.

**Comment by rgrannell1** [comment] 2020-10-18 21:41
thanks for the update! It might be obvious, but in case anyone else lands here this issue can be mitigated by running tap against the compiled typescript codebase

```
npx tsc && npx tap dist/tests
```

I have noticed this seems to break coverage detection, which might be related

**Comment by dchambers** [comment] 2020-11-03 17:31
For me the problem went away when I set `allowJs` to `false` in my `tsconfig.json`.

**Comment by rgrannell1** [comment] 2020-11-23 22:10
I found a variant with `tap --no-coverage` set. 

```
git clone git@github.com:rgrannell1/revexp.git
git checkout d573f45
yarn
```
**Control Test**

this should pass within a few minutes
```
yarn test
```
**Failing Test**
update `tsconfig` `declaration` to true. Then:
```
yarn test    // which is npm run tsc && npx tap dist/test --no-esm --no-coverage --timeout 300
```
should fail. I also saw a similar error when an import in my `ts` file didn't include a `.js` extension (with coverage enabled). I don't have a fix, but I hope my description makes things the source of the error more obvious

**Comment by erayalakese** [comment] 2020-12-03 12:38
Hello,

Any updates for this issue?

**Comment by teomurgi** [comment] 2021-02-08 10:30
Hi, any update on this?

**Comment by jes708** [comment] 2021-02-08 19:59
Hi folks,

I recently set up an app where I needed to run tap with typescript and wanted to share a solution you could try.

I would first recommend a few tweaks to your provided tsconfig.json. Namely, removing `allowJs`, change `module` to `CommonJS`, and change `target` to `ES2019` (useful if you need to support modern ES proposals such as optional chaining).

**tsconfig.json**

> ```json
> {
>   "compilerOptions": {
>     "moduleResolution": "node",
>     "module": "CommonJS",
>     "outDir": "out",
>     "allowSyntheticDefaultImports": true,
>     "noImplicitAny": true,
>     "alwaysStrict": true,
>     "strictNullChecks": true,
>     "target": "ES2019"
>   },
>   "exclude": [
>     "node_modules",
>     "out"
>   ]
> }
> ```

The next part of the solution relies on `ts-node`, so make sure to install it as a devDependency (`npm i -D ts-node`).

Then run tap with `npx tap --node-arg=--require=ts-node/register`. This will accomplish what you were trying to do with `allowJs`, as `ts-node` will work to transpile any TypeScript that is imported by your .js files.

I hope these steps work for you or at least give you some ideas of what to try next if your issue is a bit different.

**Comment by jes708** [comment] 2021-02-08 20:01
Hi folks,

I recently set up an app where I needed to run tap with typescript and wanted to share a solution you could try.

I would first recommend a few tweaks to your provided tsconfig.json. Namely, removing `allowJs`, change `module` to `CommonJS`, and change `target` to `ES2019` (useful if you need to support modern ES proposals such as optional chaining).

**tsconfig.json**

> ```json
> {
>   "compilerOptions": {
>     "moduleResolution": "node",
>     "module": "CommonJS",
>     "outDir": "out",
>     "allowSyntheticDefaultImports": true,
>     "noImplicitAny": true,
>     "alwaysStrict": true,
>     "strictNullChecks": true,
>     "target": "ES2019"
>   },
>   "exclude": [
>     "node_modules",
>     "out"
>   ]
> }
> ```

The next part of the solution relies on `ts-node`, so make sure to install it as a devDependency (`npm i -D ts-node`).

Then run tap with `npx tap --node-arg=--require=ts-node/register`. This will accomplish what you were trying to do with `allowJs`, as `ts-node` will work to transpile any TypeScript that is imported by your .js files.

I hope these steps work for you or at least give you some ideas for what to try next if your issue is a bit different.

**Comment by alexgoldstone** [comment] 2021-02-18 01:58
This is what I have landed on. It supports typescript and retains support for code coverage.

**Scroll to the bottom for interesting information regarding the tap 15 beta.**

For tsconfig.json I set:
```
"allowJs": false
```

In package.json I use:
```
"scripts": {
    "test": "tap test/*.test.ts",
    "test:coverage": "tap --no-check-coverage test/*.test.ts"
  },

...

"nyc": {
    "require": [
      "ts-node/register/transpile-only"
    ],
    "all": true,
    "check-coverage": false,
    "cache": false,
    "include": [
      "src/**/*.ts"
    ]
  },
```

The only downside is that it was very slow compared to other test libraries.

For tap 14.11.0 I get the following stats when running `time npm run test`:
```
16.46s user 1.25s system 326% cpu 5.431 total
```

The good news is that for the tap 15.0.0-0 beta just released (**no other changes**) I get the following stats when running `time npm run test`:
```
4.38s user 0.69s system 143% cpu 3.532 total
```

A significant improvement!!!

**Comment by isaacs** [comment] 2023-09-03 18:25
`type: module`, typescript, esm and cjs, all the flavors now supported on Tap v18.

`npm i tap@pre` to try it out. Do view the [changelog](https://node-tap.org/changelog/#18.0) as a lot of things have been updated.

**Closed as completed by isaacs** 2023-09-03 18:25 UTC
